name: Téléchargement BBD auto

on:
  schedule:
    - cron: '0 5 * * *'  # Tous les jours à 7h (heure de Paris)
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  download-bbd:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install requests

      - name: Lancer le script Python
        run: python download_bbd.py
