name: Téléchargement BDD auto

on:
  schedule:
    - cron: '0 5 * * *'  # Tous les jours à 7h (heure de Paris)
  workflow_dispatch:

jobs:
  download-bdd:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: pip install requests

      - name: Lancer le script Python
        run: python download_bbd.py

      - name: Ajouter le fichier CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*.csv
          git commit -m "✅ Fichier mis à jour automatiquement"
          git push
